version: 2
jobs:
  build:
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - checkout
      - run:
          name: "Install `circleci` CLI"
          command: |
            sudo bash -c "$(curl -fSl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh)"
            circleci orb
      - run: circleci orb validate ./microservices.yml
      - run: circleci orb process ./microservices.yml
  publish:
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - checkout
      - run: |
          jq -r '.name' version.json
          jq -r '.version' version.json

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - publish