version: 2
jobs:
  build:
    docker:
      - image: circleci/classic
    steps:
      - checkout
      - run: circleci orb validate ./microservices.yml
      - run: circleci orb process ./microservices.yml
  publish:
    docker:
      - image: circleci/classic
    steps:
      - checkout
      - run: |
        jq -r '.name' version.json
        jq -r '.version' version.json

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - publish