version: 2
orbs:
  cli: circleci/circleci-cli

jobs:
  build:
    executor: cli/default
    steps:
      - checkout
      - run: circleci orb validate ./microservices.yml
      - run: circleci orb process ./microservices.yml
  publish:
    executor: cli/default
    steps:
      - checkout
      - run: |
          jq -r '.name' version.json
          jq -r '.version' version.json

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - publish